### ISSUE TITLE
precompiled binaries

### ISSUE THREAD

**Issue by Bluscream** [Luch00/LxBTSC#1]
Would you provide them?

**Comment by Luch00** [comment]
[Binaries added](https://github.com/Luch00/LxBTSC/releases/latest)

**Comment by Bluscream** [comment]
Awesome, thanks :3

**Comment by Bluscream** [comment]
Could you push a new release please? I really want the toggle to switch back to normal chat with a command

**Comment by Bluscream** [comment]
Thanks for v1.2 💘
