### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by Bluscream** [Luch00/LxBTSC#24]
I created a `style.user.css` based on [teamspeak-dark](https://github.random-host.com/teamspeak-dark/):

- https://gist.github.com/Bluscream/6a8561ea5ea556c4c171ea31d9ba468b

![](https://i.imgur.com/M9qheSb.png)

**Comment by Badetuch** [comment]
How can i use this?

**Comment by Badetuch** [comment]
Thanks man 👍

**Comment by Badetuch** [comment]
Looks sick man thx ^^

**Comment by Badetuch** [comment]
I dont find the path in %appdata% there is no Ts3client Folder

**Comment by Badetuch** [comment]
Ah, now i found it looks awesome man 👍

**Comment by Badetuch** [comment]
How did you make the chat on the Right side?

**Comment by Bluscream** [comment]
> 
> 
> How did you make the chat on the Right side?

https://repo.4qt.de/ts3client-dockwidget-plugin/
