### ISSUE TITLE
[Feature Request] User Styles

### ISSUE THREAD

**Issue by Bluscream** [Luch00/LxBTSC#3]
Please allow a css file to be read on startup and injected to the WebFrame :)

**Comment by Bluscream** [comment]
I'm thinking that you could even parse the 'original' chatWidget's QSS and inject that as CSS. You'd just have to give the elements the classes they originally had :)

**Comment by Luch00** [comment]
You can edit the style by editing `style.css` in `plugins/LxBTSC/template`

**Comment by Bluscream** [comment]
Oh awesome so far, would love to still keep this open for the QSS parsing ^^

**Comment by Bluscream** [comment]
Thanks for implementing it that way. It's sad that any local changes get overwritten on update.

What about having a `style.user.css` that doesn't get generated and therefor not overwritten where i can enter my custom style properties with the `!important` modifier?
