### ISSUE TITLE
Spotify embeds broken?

### ISSUE THREAD

**Issue by Bluscream** [Luch00/LxBTSC#35]
Do the generic embeds have a higher priority?

![grafik](https://user-images.githubusercontent.com/3318223/43991301-79817b3a-9d59-11e8-9d6d-0ec69dd1ca21.png)
![grafik](https://user-images.githubusercontent.com/3318223/43991326-f9739ad0-9d59-11e8-9b77-ab95531e9647.png)

**Comment by Luch00** [comment]
Sadly spotify embeds do not work at all.
Browser version is too old for that.

**Comment by Bluscream** [comment]
Ahh okay, thats sad news but good to know :)

**Comment by Bluscream** [comment]
I wonder if there was some way for you to distribute something like a QtWebengine patch with support for more codecs and a updated CEF version
