### ISSUE TITLE
Server based emote lists

### ISSUE THREAD

**Issue by Scrxtchy** [Luch00/LxBTSC#37]
How much effort would it be to fetch an additional json file from the default channel of a server?
It would be interesting feature if server admins would be able to define these in a file stored on the server itself, allowing all the clients to see them, without having to define these in their own configurations.

**Comment by Luch00** [comment]
Added in [this release.](https://github.com/Luch00/LxBTSC/releases/tag/1.11)
Drop a file named `emotes.json` on the default channel and it should work.

**Comment by Scrxtchy** [comment]
Hmm, might need a small revision.
If the client has no perms for `i_ft_needed_file_browse_power`, the client will alert to this
and if the file does not exist, a `file input/output error` is also given an alert.

Otherwise, I'm assuming this works very well

**Comment by Bluscream** [comment]
This needs sending and catching returncodes

**Comment by Luch00** [comment]
Catching these errors in ts3plugin_onServerErrorEvent or ts3plugin_onServerPermissionErrorEvent doesn't seem to do anything. 
There error is printed to chat and an alert given even if the error is supposedly handled by the plugin.

**Comment by Bluscream** [comment]
You need to use .createReturnCode() for some reason

**Comment by Luch00** [comment]
Thank you, that is what I was missing.
And it was not mentioned anywhere in the documentation.

**Comment by Bluscream** [comment]
No problem. This gave me several headaches too

**Comment by Bluscream** [comment]
Glad i could help finally.
