### ISSUE TITLE
Is it possible to add more emotes? 

### ISSUE THREAD

**Issue by Disgame** [Luch00/LxBTSC#46]
Hey I'd like to know if it's possible to create ur own emotes/gifs and add them as an "addon" or "pack". Would appreciate :)

**Comment by Luch00** [comment]
Yes, you can see how the default emotes are added if you browser to the plugin directory and look at the json files.
Basically you need the .json file where the emote code and url or filepath are defined, for example:
```json
{
    "setname": "Title of this emote pack",
    "pathbase": "",
    "pathappend": "",
    "emoticons": 
    [
        { "code": "FunnyEmote", "name": "https://i.imgur.com/sdgoYyE.gif" },
        { "code": "FunnyEmote2", "name": "some_other_url" }
    ]
}
```
And to share this definition file you can

1. upload it to the default channel of the server as `emotes.json` and the plugin will download it from there when connecting, this of course requires that users have a permission to download from the channel.
2. host the .json file somewhere and add the url into the textbox in the plugin settings
3. share it like a regular teamspeak icon pack and have all the files locally in the plugin directory

**Comment by Disgame** [comment]
Thanks for your answer, I will try it out later :)
