### ISSUE TITLE
Dependencies?

### ISSUE THREAD

**Issue by Bluscream** [Luch00/LxBTSC#8]
Can you provide some infos on the dependencies?

It seems like you didn't include Teamspeaks plugin api, i figured i'd have to put their files in `QtLxBTSC/teamspeak` and `QtLxBTSC/teamlog`.

What about the missing `bbcode_parser.h`? Is it https://github.com/mrataj/BBCodeParser ?

**Comment by Luch00** [comment]
Teamspeak plugin api files are in in the project directory `/ts_plugin/include`

BBCode parser that I've used for now is [bbcodelib](https://sourceforge.net/projects/bbcodelib/)
Updated the repository to include those files

**Comment by Bluscream** [comment]
For some reason VS searched for the pluginAPI stuff in `QtLxBTSC/teamspeak` :o 
thanks for adding the lib ^^

**Comment by Luch00** [comment]
Google tells me `Foundation/Foundation.h` is part of Apples frameworks, none of that should be necessary here and none of that is being used by me 🤔 

Besides the files in this repository only Qt 5.6 libraries should be necessary.

**Comment by Bluscream** [comment]
Do you maybe have a teamspeak where others can meet you and resolve such issues? ^^

**Comment by Bluscream** [comment]
Could you maybe help me with these strange problems? I'd like to contribute to your project by doing the time-consuming work of adding additional events to be shown in the chat. Group-changes, etc. etc.

**Comment by Luch00** [comment]
I have now changed to a javascript bbcode parser so the file causing your error above isn't included anymore, try again if there are any more problems.

**Comment by Bluscream** [comment]
Thanks i will try it soon 👍

**Comment by Bluscream** [comment]
Now after retrying with your latest changes i am able to compile it but get 

on client start
`Entry point not found...`
and this

when i look at the plugin in the addon list
![grafik](https://user-images.githubusercontent.com/3318223/32894202-65799dc0-cadc-11e7-94d4-cc8dc4d98509.png)
Using

Visual Studio 2017
Visual Studio 2015 (v140) toolset
Windows 8.1/10 SDK
Qt Visual Studio Tools
Qt 5.6.3 ([Couldn't find 5.6.2 in the Qt installer](https://user-images.githubusercontent.com/3318223/32894129-2d3b8e46-cadc-11e7-8ecf-0ff95b1eff71.png))

**Comment by Bluscream** [comment]
Any clue whats wrong here?

**Comment by Luch00** [comment]
Qt version is wrong, use the 5.6 on the installer

**Comment by Bluscream** [comment]
That works fine, thanks :) Expect some stuff in the next days but currently i'm a bit busy with

- Bluscream/Teamspeak-Server-In-Server
- Bluscream/TS3AudioBotPlugins
- ReSpeak/TS3Hook
- Splamy/TS3AudioBot
